### ISSUE TITLE
Just can't enable extensions

### ISSUE THREAD

**Issue by kdidenko** [GeorgesStavracas/gedit-markdown#8]
After installing this extension according to the README.md manual, as soon  as I'm trying to enable it through Gedit's GUI (e.g.: _edit > preferences > "Markdown Preview"_) it throws me an error to console: 

````bash
/home/user/.local/share/gedit/plugins/gedit-markdown/win.py:1: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, GObject, Gio, Gtk, Gedit, WebKit2

(gedit:19267): libpeas-WARNING **: Error importing plugin 'gedit-markdown':
Traceback (most recent call last):
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/user/.local/share/gedit/plugins/gedit-markdown/__init__.py", line 2, in <module>
    from .win import MdWinActivatable
  File "/home/user/.local/share/gedit/plugins/gedit-markdown/win.py", line 3, in <module>
    from .parser import MdParser
  File "/home/user/.local/share/gedit/plugins/gedit-markdown/parser.py", line 2, in <module>
    import markdown
ImportError: No module named 'markdown'

(gedit:19267): libpeas-WARNING **: Error loading plugin 'gedit-markdown'
````
**System specs:**
`user@ubuntu:~$ **uname -a**
Linux ubuntu 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
```
user@ubuntu:~$ **lsb_release -a**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
**Gedit:** v.3.18.3

**Comment by haeckle** [comment]
You missed to install the 'python-markdown' dependency.
A simple 

> sudo apt install python3-markdown

should do the trick

Edit: Probably the Python3 version is needed

**Comment by haeckle** [comment]
probably the same as #6
